-- Create ticket_views table to track which tickets have been seen by users
CREATE TABLE IF NOT EXISTS ticket_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id UUID NOT NULL,
    user_email TEXT NOT NULL,
    viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_read BOOLEAN DEFAULT false,
    UNIQUE(ticket_id, user_email),
    CONSTRAINT fk_ticket_views_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_ticket_views_user_email ON ticket_views(user_email);
CREATE INDEX IF NOT EXISTS idx_ticket_views_ticket_id ON ticket_views(ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_views_is_read ON ticket_views(is_read);
